# 作業目標:
    了解 Convolution 卷積的組成

# 作業重點:
    修改 a_slice_prev, 檢查 Z 的輸出

In [1]:
import numpy as np

In [2]:
# GRADED FUNCTION: conv_single_step
def conv_single_step(a_slice_prev, W, b):
    """
    定義一層 Kernel (內核), 使用的參數說明如下
    Arguments:
        a_slice_prev -- 輸入資料的維度
        W -- 權重, 被使用在 a_slice_prev
        b -- 偏差參數 
    Returns:
        Z -- 滑動窗口（W，b）卷積在前一個 feature map 上的結果
    """

    # 定義一個元素介於 a_slice and W
    s = a_slice_prev * W
    # 加總所有的 "s" 並指定給Z.
    Z = np.sum(s)
    # Add bias b to Z. 這是 float() 函數,
    Z = float(Z + b)

    return Z

In [4]:


np.random.seed(1)
#定義一個 axaxd 的 feature map
a_slice_prev = np.random.randn(5, 5, 3)
W = np.random.randn(5, 5, 3)
b = np.random.randn(1, 1, 1)

print('W', W)
#取得計算後,卷積矩陣的值
Z = conv_single_step(a_slice_prev, W, b)
print("Z =", Z)


W [[[-2.02220122 -0.30620401  0.82797464]
  [ 0.23009474  0.76201118 -0.22232814]
  [-0.20075807  0.18656139  0.41005165]
  [ 0.19829972  0.11900865 -0.67066229]
  [ 0.37756379  0.12182127  1.12948391]]

 [[ 1.19891788  0.18515642 -0.37528495]
  [-0.63873041  0.42349435  0.07734007]
  [-0.34385368  0.04359686 -0.62000084]
  [ 0.69803203 -0.44712856  1.2245077 ]
  [ 0.40349164  0.59357852 -1.09491185]]

 [[ 0.16938243  0.74055645 -0.9537006 ]
  [-0.26621851  0.03261455 -1.37311732]
  [ 0.31515939  0.84616065 -0.85951594]
  [ 0.35054598 -1.31228341 -0.03869551]
  [-1.61577235  1.12141771  0.40890054]]

 [[-0.02461696 -0.77516162  1.27375593]
  [ 1.96710175 -1.85798186  1.23616403]
  [ 1.62765075  0.3380117  -1.19926803]
  [ 0.86334532 -0.1809203  -0.60392063]
  [-1.23005814  0.5505375   0.79280687]]

 [[-0.62353073  0.52057634 -1.14434139]
  [ 0.80186103  0.0465673  -0.18656977]
  [-0.10174587  0.86888616  0.75041164]
  [ 0.52946532  0.13770121  0.07782113]
  [ 0.61838026  0.23249456  0.